// <auto-generated />
namespace ListMe.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UserToItemnav : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserToItemnav));
        
        string IMigrationMetadata.Id
        {
            get { return "201304150755097_UserToItemnav"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
